START TRANSACTION;

DROP TABLE ASSOC_USER_WORK CASCADE;
DROP TABLE ASSOC_TYPE_WORK CASCADE;
DROP TABLE ASSOC_ARTIST_WORK CASCADE;
DROP TABLE TYPE CASCADE;
DROP TABLE WORK CASCADE;
DROP TABLE ARTIST CASCADE;
DROP TABLE USERS CASCADE;

COMMIT;

